#!/bin/bash

# set some colors
CNT="[\e[1;36mNOTE\e[0m]"
COK="[\e[1;32mOK\e[0m]"
CER="[\e[1;31mERROR\e[0m]"
CAT="[\e[1;37mATTENTION\e[0m]"
CWR="[\e[1;35mWARNING\e[0m]"
CAC="[\e[1;33mACTION\e[0m]"
INSTLOG="install.log"

sleep 1

echo -e "\n$CNT - Installing fcitx5, this may take a while..."
for SOFTWR in fcitx5-im fcitx5-chinese-addons fcitx5-qt fcitx5-gtk
do
    #First lets see if the package is there
    if pacman -Qs $SOFTWR > /dev/null ; then
        echo -e "$COK - $SOFTWR is already installed."
    else
        echo -e "$CNT - Now installing $SOFTWR ..."
        sudo pacman -S --noconfirm $SOFTWR &>> $INSTLOG
        if pacman -Qs $SOFTWR > /dev/null ; then
            echo -e "$COK - $SOFTWR was installed."
        else
            echo -e "$CER - $SOFTWR install had failed, please check the install.log"
            exit
        fi
    fi
done